config/routes.rb
Rails.application.routes.draw do
  
  resources :tenants do 
	resources :members do
		collection do 
			post :invite	
		end 
	end 
  end
  devise_for :users
  root 'static_pages#landing_page'
  get 'dashboard', to: 'static_pages#dashboard'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  belongs_to :tenant
end

app/models/tenant.rb
class Tenant < ApplicationRecord
	validates :name, presence: true
	has_many :members 
	has_many :users, through: :members 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :members 
  has_many :tenants, through: :members 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/authorize_controller.rb
class AuthorizeController < ApplicationController 
	before_action :set_current_tenant 
	before_action :authorize_member 
	
	private 

	def set_current_tenant 
		@current_tenant = Tenant.find(params[:tenant_id])
	end

	def authorize_member
        return redirect_to root_path, alert: 'You are not a member' unless @current_tenant.users.include? current_user
    end
end 

app/controllers/members_controller.rb
class MembersController < AuthorizeController
	

	def index 
		@member = @current_tenant.members 
	end 

	def invite
		email =params[:email]
		return redirect_to tenant_members_path(@current_tenant), alert: 'No email provided' if email.blank?

		user = User.find_by(email:) || User.invite!({ email: }, current_user)
		return redirect_to tenant_members_path(@current_tenant), alert: 'Email invalid' unless user.valid?
		
		user.members.find_or_create_by(tenant: @current_tenant, roles: {admin: false, editor: true})
		#binding.b
		redirect_to tenant_members_path(@current_tenant), notice: '#{email} Invited'
	end

	 
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	skip_before_action :authenticate_user!, only: :landing_page

  def landing_page
  end

  def dashboard
  end
end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
  before_action :set_tenant, only: %i[ show edit update destroy ]
  before_action :authorize_member, only: %i[ show edit update destroy ]
  # GET /tenants or /tenants.json
  def index
    @tenants = current_user.tenants
  end

  # GET /tenants/1 or /tenants/1.json
  def show
    
  end

  # GET /tenants/new
  def new
    @tenant = Tenant.new
  end

  # GET /tenants/1/edit
  def edit
  end

  # POST /tenants or /tenants.json
  def create
    @tenant = Tenant.new(tenant_params)

    respond_to do |format|
      if @tenant.save
        @tenant.members.create(user: current_user, roles: {admin: true})
        format.html { redirect_to tenant_url(@tenant), notice: "Tenant was successfully created." }
        format.json { render :show, status: :created, location: @tenant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tenant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tenants/1 or /tenants/1.json
  def update
    respond_to do |format|
      if @tenant.update(tenant_params)
        format.html { redirect_to tenant_url(@tenant), notice: "Tenant was successfully updated." }
        format.json { render :show, status: :ok, location: @tenant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tenant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tenants/1 or /tenants/1.json
  def destroy
    @tenant.destroy!

    respond_to do |format|
      format.html { redirect_to tenants_url, notice: "Tenant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def authorize_member
        return redirect_to root_path, alert: 'You are not a member' unless @tenant.users.include? current_user
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_tenant
      @tenant = Tenant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tenant_params
      params.require(:tenant).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Multitenancy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= link_to 'Home', root_path %>
        <% if signed_in? %>
            <%= link_to 'Dashboard', dashboard_path %>
            <%= link_to 'Tenants', tenants_path %>
            <%= link_to current_user.email, edit_user_registration_path %>
            <%= button_to "Log out", destroy_user_session_path, method: :delete, data: { turbo: "false" } %>
        <% else %>
            <%= link_to "Log in", new_user_session_path %>
            <%= link_to "Register", new_user_registration_path %>
        <% end %>
        
        <%= yield %>
  </body>
</html>

app/views/members/index.html.erb
<h1> Invite Members </h1>

<%= form_with url: invite_tenant_members_path do |form| %>
	<%= form.text_field :email, placeholder: 'Email' %>
	<%= form.submit 'Invite members' %>
<% end %>

<h1>Members</h1>

<% @member.each do |member| %>
	<%= member.user.email %>
	<%= member.roles %>
<% end %>

app/views/static_pages/dashboard.html.erb
<h1>StaticPages#dashboard</h1>
<p>Find me in app/views/static_pages/dashboard.html.erb</p>

app/views/static_pages/landing_page.html.erb
<h1>StaticPages#landing_page</h1>
<p>Find me in app/views/static_pages/landing_page.html.erb</p>

app/views/tenants/_form.html.erb
<%= form_with(model: tenant) do |form| %>
  <% if tenant.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tenant.errors.count, "error") %> prohibited this tenant from being saved:</h2>

      <ul>
        <% tenant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tenants/_tenant.html.erb
<div id="<%= dom_id tenant %>">
  <p>
    <strong>Name:</strong>
    <%= tenant.name %>
  </p>

</div>

app/views/tenants/edit.html.erb
<h1>Editing tenant</h1>

<%= render "form", tenant: @tenant %>

<br>

<div>
  <%= link_to "Show this tenant", @tenant %> |
  <%= link_to "Back to tenants", tenants_path %>
</div>

app/views/tenants/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tenants</h1>

<div id="tenants">
  <% @tenants.each do |tenant| %>
    <%= render tenant %>
    <p>
      <%= link_to "Show this tenant", tenant %>
    </p>
  <% end %>
</div>

<%= link_to "New tenant", new_tenant_path %>

app/views/tenants/new.html.erb
<h1>New tenant</h1>

<%= render "form", tenant: @tenant %>

<br>

<div>
  <%= link_to "Back to tenants", tenants_path %>
</div>

app/views/tenants/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tenant %>

<div>
  <%= link_to "Edit this tenant", edit_tenant_path(@tenant) %> |
  <%= link_to "Back to tenants", tenants_path %>

  <%= button_to "Destroy this tenant", @tenant, method: :delete %>
</div>

<%= link_to 'Members', tenant_members_path(@tenant) %>